cart/urls.py
from django.urls import path

from .views import (cart_detail_view, add_to_cart_view, remove_from_cart, clear_cart, )


app_name = "cart"


urlpatterns = [
    path('', cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>/', add_to_cart_view, name='cart_add'),
    path('remove/<int:product_id>/', remove_from_cart, name='cart_remove'),
    path('clear/', clear_cart, name='cart_clear'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('allauth.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
    path('payment/', include('payment.urls')),

#     rosetta(i18n)
    path('rosetta/', include('rosetta.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from .views import (ProductListView, ProductDetailView, CommentCreateView, test_translation)
app_name = 'product'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('comment/<int:pk>/', CommentCreateView.as_view(), name='product_comment'),
    path('test_hello/', test_translation,),
]

templates/_base.html
{% load static %}
{% load i18n %}
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">


    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static favicon.ico%}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static icon.png%}">

    <!-- ************************* CSS Files ************************* -->

    <link rel="stylesheet" href="{% static 'css/_base.css' %}">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="{% static 'css/vendor.css' %}">

    <!-- style css -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">



    <title>{% block title %}{% endblock title %}</title>
</head>
<body dir='rtl'>

        <!-- Header Start -->
        <header class="header">
            <div class="header-inner fixed-header">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-9 col-lg-8 col-5 col-xs-0 col-none col-sm-block p-0">
                            <nav class="main-navigation">
                                <div class="site-branding" style="margin-right: 30px;">
                                    <a href="index.html" class="logo">
                                        <figure class="logo--normal d-none d-sm-block">
                                            <img class="px-5" src="{% static 'img/codingyar_logo.png' %}" style="max-height: 50px; margin-bottom: -15px;" alt="Logo">
                                        </figure>
                                    </a>
                                </div>
                                <div class="mainmenu-nav d-none d-lg-block w-100 pr-3">
                                    <ul class="mainmenu d-lg-flex jusity-content-end jusity-content-lg-start pt-4">
                                        <li class="mainmenu__item menu-item-has-children active">
                                            <a href="{% url 'home' %}" class="mainmenu__link">
                                                <span class="mm-text">خانه</span>
                                            </a>
                                        </li>
                                        <li class="mainmenu__item menu-item-has-children">
                                            <a href="{% url 'product:product_list' %}" class="mainmenu__link">
                                                <span class="mm-text">وبلاگ</span>
                                            </a>
                                        </li>
                                        <li class="mainmenu__item menu-item-has-children">
                                            <a href="#" class="mainmenu__link">
                                                <span class="mm-text">صفحات</span>
                                            </a>
                                         </li>
                                        <li class="mainmenu__item">
                                            <a href="contact-us.html" class="mainmenu__link">
                                                <span class="mm-text">تماس با ما</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                        <div class="col-xl-3 col-lg-4 col-sm-7 col-12 p-0">
                            <ul class="header-toolbar">
                                <li class="header-toolbar__item">
                                    <a href="wishlist.html" class="header-toolbar__btn mx-4">
                                        <i class="flaticon flaticon-like"></i>
                                    </a>
                                </li>
                                <li class="header-toolbar__item mini-cart-item">
                                    <a href="#miniCart" class="header-toolbar__btn toolbar-btn mini-cart-btn">
                                        <i class="flaticon flaticon-shopping-cart"></i>
                                        <sup class="mini-cart-count">{{ cart|length }}</sup>
                                    </a>
                                </li>
                                <li class="header-toolbar__item user-info">
                                    <a href="my-account.html" class="header-toolbar__btn">
                                        <i class="flaticon flaticon-user"></i>
                                    </a>
                                    <ul class="user-info-menu">
                                        {% if user.is_authenticated %}
                                            <li>
                                                <a class="text-right" href="{% url 'account_logout' %}">{% trans 'Logout' %}</a>
                                            </li>

                                            <li>

{#                                                <a class="text-right" href="{% url 'profile' %}">{% trans 'Profile' %}</a>#}
                                            </li>
                                        {% else %}
                                            <li>
                                                <a class="text-right" href="{% url 'account_login' %}">{% translate 'Login' %}</a>
                                            </li>
                                            <li>
                                                <a class="text-right" href="{% url 'account_signup' %}">{% translate 'Signup' %}</a>
                                            </li>
                                        {% endif %}

                                    </ul>
                                </li>
                                <li class="header-toolbar__item">
                                    <a href="#searchForm" class="header-toolbar__btn toolbar-btn">
                                        <i class="flaticon flaticon-search"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="mobile-menu"></div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Header End -->
{##}
{#    <!-- Preloader Start -->#}
{#    <div class="ShoppingYar-preloader active">#}
{#        <div class="ShoppingYar-preloader-inner h-100 d-flex align-items-center justify-content-center">#}
{#            <div class="ShoppingYar-child ShoppingYar-bounce1"></div>#}
{#            <div class="ShoppingYar-child ShoppingYar-bounce2"></div>#}
{#            <div class="ShoppingYar-child zuka-bounce3"></div>#}
{#        </div>#}
{#    </div>#}
{#    <!-- Preloader End -->#}





{#    {% if user.is_authenticated %}#}
{#        <span>Hello {{ user.userimail }}</span> --- | --- <a href="{% url 'account_logout' %}">log out</a>#}
{#    {% else %}#}
{#        <a href="{% url 'account_login' %}">log in</a> ___ | ___ <a href="{% url 'account_signup' %}">sign up</a>#}
{#    {% endif %}#}

<div class="row py-1">
<div class="col-md-4 col-md-3 mx-auto">
    {% if messages %}
    <div class="container">{% for m in messages %}
        <div class="alert alert-{{ m.tags }}">{{ m }}</div>
    {% endfor %}</div>

{% endif %}
</div>
</div>
<div class="row py-3">
<div class="col-md-8 col-md-10 mx-auto">
{% block content %}

{% endblock content %}



</div>
</div>
{% include 'footer.html' %}
    <!-- Main Wrapper End -->
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>




    <!-- ************************* JS Files ************************* -->

    <!-- jQuery JS -->
    <script src="{% static 'js/vendor.js' %}"></script>

    <!-- Main JS -->
    <script src="{% static 'js/main.js' %}"></script>
<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->


</body>
</html>

templates/footer.html
{% load static %}
        <!-- Footer Start-->
        <footer class="footer">
            <div class="footer-top bg-color ptb--50" data-bg-color="#f6f6f6">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-9 text-center">
                            <div class="footer-widget mb--50">
                                <div class="textwidget">
                                    <img src="{% static 'img/codingyar_logo.png' %}" alt="Logo">
                                </div>
                            </div>
                            <div class="footer-widget mb--50 pb--1">
                                <ul class="footer-menu">
                                    <li><a href="">درباره ما</a></li>
                                    <li><a href="">قوانین و مقررات</a></li>
                                    <li><a href="">تماس با ما</a></li>
                                </ul>
                            </div>
                            <div class="footer-widget">
                                Codingyar.com © | all rights reserved
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Footer End-->

templates/home.html
{% extends '_base.html' %}
{% block title %}
    home
{% endblock %}
{% block content %}
WELCOME TO HOME !
{% endblock %}

templates/topheader.html
{% load i18n %}



    <!-- Breadcrumb area Start -->
    <div class="breadcrumb-area bg-color ptb--90" data-bg-color="#f6f6f6">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="d-flex justify-content-between align-items-center flex-sm-row flex-column">
                        <h1 class="page-title">{{ d }}  . {{ heder_name }} .</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb area End -->